apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: datascientest-charge-pod
spec:
  containers:
    - args:
        - cpu
      image: nginx
      name: charge-pod
      resources:
        requests:
          memory: "3000Mi"
          cpu: "2"
        limits:
          memory: "3000Mi"
          cpu: "2"